-- Tenant
CREATE TABLE TENANTS (
    TENANT_ID VARCHAR(20) NOT NULL,
    TENANT_NAME VARCHAR(100),
    TENANT_DESCRIPTION VARCHAR(255),
    USE_AT CHAR(1),
    CREATED_DATE DATETIME,
    PRIMARY KEY (TENANT_ID)
);

-- Common Code
CREATE TABLE COMMON_CODES (
    CODE_ID VARCHAR(6) NOT NULL,
    CLASS_CODE VARCHAR(3),
    CODE_NAME VARCHAR(60),
    CODE_DESCRIPTION VARCHAR(200),
    USE_AT CHAR(1),
    TENANT_ID VARCHAR(20),
    PRIMARY KEY (CODE_ID)
);

-- File
CREATE TABLE FILES (
    ATTACHMENT_FILE_ID VARCHAR(20) NOT NULL,
    CREATED_DATETIME DATETIME,
    USE_AT CHAR(1),
    TENANT_ID VARCHAR(20),
    PRIMARY KEY (ATTACHMENT_FILE_ID)
);

CREATE TABLE FILE_DETAILS (
    DETAIL_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    ATTACHMENT_FILE_ID VARCHAR(20),
    FILE_SEQUENCE INT,
    FILE_STORED_PATH VARCHAR(2000),
    STORED_FILE_NAME VARCHAR(255),
    ORIGINAL_FILE_NAME VARCHAR(255),
    FILE_EXTENSION VARCHAR(20),
    FILE_CONTENT TEXT,
    FILE_SIZE BIGINT,
    FOREIGN KEY (ATTACHMENT_FILE_ID) REFERENCES FILES(ATTACHMENT_FILE_ID)
);

-- Admin
CREATE TABLE ROLES (
    ROLE_ID VARCHAR(20) NOT NULL,
    ROLE_NAME VARCHAR(60),
    ROLE_PATTERN VARCHAR(300),
    ROLE_DESCRIPTION VARCHAR(200),
    ROLE_TYPE VARCHAR(80),
    ROLE_SORT_ORDER VARCHAR(10),
    ROLE_CREATED_DATE DATETIME,
    TENANT_ID VARCHAR(20),
    PRIMARY KEY (ROLE_ID)
);

CREATE TABLE USERS (
    ESNTL_ID VARCHAR(20) NOT NULL,
    USER_ID VARCHAR(20) UNIQUE,
    PASSWORD VARCHAR(200),
    USER_NAME VARCHAR(60),
    EMAIL VARCHAR(50),
    ZIP_CODE VARCHAR(6),
    USER_ADDRESS VARCHAR(100),
    USER_EMAIL VARCHAR(50),
    GROUP_ID VARCHAR(20),
    ORGANIZATION_ID VARCHAR(20),
    INSTITUTION_CODE VARCHAR(8),
    STATUS_CODE VARCHAR(15),
    ROLE_ID VARCHAR(20),
    TENANT_ID VARCHAR(20),
    SUBSCRIBED_DATE DATETIME,
    PRIMARY KEY (ESNTL_ID),
    FOREIGN KEY (ROLE_ID) REFERENCES ROLES(ROLE_ID)
);

CREATE TABLE MENUS (
    MENU_NO BIGINT NOT NULL,
    MENU_NAME VARCHAR(60),
    PROGRAM_FILE_NAME VARCHAR(60),
    MENU_ORDER INT,
    MENU_DESCRIPTION VARCHAR(250),
    UPPER_MENU_NO BIGINT,
    RELATE_IMAGE_PATH VARCHAR(100),
    RELATED_IMAGE_NAME VARCHAR(60),
    TENANT_ID VARCHAR(20),
    PRIMARY KEY (MENU_NO)
);
