-- =====================================================
-- CRM Project - Initial Schema Migration
-- Version: V1
-- Description: Creates all core tables for multi-tenant CRM system
-- Author: CRM Project Team
-- Date: 2026-01-22
-- =====================================================

-- =====================================================
-- 1. TENANT MANAGEMENT
-- =====================================================

-- Main tenant table
CREATE TABLE TENANTS (
    TENANT_ID VARCHAR(20) NOT NULL,
    TENANT_NAME VARCHAR(100),
    TENANT_DESCRIPTION VARCHAR(255),
    USE_AT CHAR(1) DEFAULT 'Y',
    CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_DATE TIMESTAMP,
    PRIMARY KEY (TENANT_ID)
);

-- =====================================================
-- 2. ORGANIZATIONAL HIERARCHY
-- =====================================================

-- Branch: Physical locations under a tenant
CREATE TABLE BRANCHES (
    BRANCH_ID VARCHAR(20) NOT NULL,
    BRANCH_NAME VARCHAR(100) NOT NULL,
    BRANCH_CODE VARCHAR(20) UNIQUE NOT NULL,
    BRANCH_ADDRESS VARCHAR(255),
    BRANCH_PHONE VARCHAR(20),
    PARENT_BRANCH_ID VARCHAR(20),
    TENANT_ID VARCHAR(20) NOT NULL,
    USE_AT CHAR(1) DEFAULT 'Y',
    CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_DATE TIMESTAMP,
    PRIMARY KEY (BRANCH_ID),
    FOREIGN KEY (TENANT_ID) REFERENCES TENANTS(TENANT_ID) ON DELETE CASCADE,
    FOREIGN KEY (PARENT_BRANCH_ID) REFERENCES BRANCHES(BRANCH_ID)
);
CREATE INDEX IDX_BRANCHES_TENANT ON BRANCHES(TENANT_ID);

-- Group: Departments or teams within a branch
CREATE TABLE GROUPS (
    GROUP_ID VARCHAR(20) NOT NULL,
    GROUP_NAME VARCHAR(100) NOT NULL,
    GROUP_CODE VARCHAR(20) NOT NULL,
    GROUP_DESCRIPTION VARCHAR(255),
    BRANCH_ID VARCHAR(20) NOT NULL,
    TENANT_ID VARCHAR(20) NOT NULL,
    USE_AT CHAR(1) DEFAULT 'Y',
    CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_DATE TIMESTAMP,
    PRIMARY KEY (GROUP_ID),
    FOREIGN KEY (BRANCH_ID) REFERENCES BRANCHES(BRANCH_ID) ON DELETE CASCADE,
    FOREIGN KEY (TENANT_ID) REFERENCES TENANTS(TENANT_ID) ON DELETE CASCADE,
    UNIQUE (GROUP_CODE, TENANT_ID)
);
CREATE INDEX IDX_GROUPS_TENANT ON GROUPS(TENANT_ID);
CREATE INDEX IDX_GROUPS_BRANCH ON GROUPS(BRANCH_ID);

-- Position: Job titles/positions within the organization
CREATE TABLE POSITIONS (
    POSITION_ID VARCHAR(20) NOT NULL,
    POSITION_NAME VARCHAR(100) NOT NULL,
    POSITION_CODE VARCHAR(20) NOT NULL,
    POSITION_LEVEL INT DEFAULT 0,
    POSITION_DESCRIPTION VARCHAR(255),
    TENANT_ID VARCHAR(20) NOT NULL,
    USE_AT CHAR(1) DEFAULT 'Y',
    CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_DATE TIMESTAMP,
    PRIMARY KEY (POSITION_ID),
    FOREIGN KEY (TENANT_ID) REFERENCES TENANTS(TENANT_ID) ON DELETE CASCADE,
    UNIQUE (POSITION_CODE, TENANT_ID)
);
CREATE INDEX IDX_POSITIONS_TENANT ON POSITIONS(TENANT_ID);

-- =====================================================
-- 3. MENU & PERMISSION SYSTEM
-- =====================================================

-- Menus table with enhanced fields for permission generation
CREATE TABLE MENUS (
    MENU_NO BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    MENU_CODE VARCHAR(50) UNIQUE NOT NULL,
    MENU_NAME VARCHAR(100) NOT NULL,
    MENU_TYPE VARCHAR(20) DEFAULT 'MENU',
    MENU_PATH VARCHAR(255),
    API_ENDPOINT VARCHAR(255),
    ICON_NAME VARCHAR(50),
    UPPER_MENU_NO BIGINT,
    MENU_ORDER INT DEFAULT 0,
    MENU_DESCRIPTION VARCHAR(255),
    IS_VISIBLE CHAR(1) DEFAULT 'Y',
    IS_ACTIVE CHAR(1) DEFAULT 'Y',
    TENANT_ID VARCHAR(20) NOT NULL,
    CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_DATE TIMESTAMP,
    CREATED_BY VARCHAR(20),
    FOREIGN KEY (TENANT_ID) REFERENCES TENANTS(TENANT_ID) ON DELETE CASCADE,
    FOREIGN KEY (UPPER_MENU_NO) REFERENCES MENUS(MENU_NO)
);
CREATE INDEX IDX_MENUS_TENANT ON MENUS(TENANT_ID);
CREATE INDEX IDX_MENUS_CODE ON MENUS(MENU_CODE);
CREATE INDEX IDX_MENUS_PARENT ON MENUS(UPPER_MENU_NO);

-- Permissions table (auto-generated from menus)
CREATE TABLE PERMISSIONS (
    PERMISSION_ID BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    PERMISSION_CODE VARCHAR(100) NOT NULL,
    PERMISSION_TYPE VARCHAR(20) NOT NULL,
    PERMISSION_ACTION VARCHAR(20) NOT NULL,
    RESOURCE_PATH VARCHAR(255),
    DESCRIPTION VARCHAR(255),
    MENU_NO BIGINT,
    TENANT_ID VARCHAR(20),
    CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_DATE TIMESTAMP,
    CREATED_BY VARCHAR(20),
    FOREIGN KEY (MENU_NO) REFERENCES MENUS(MENU_NO) ON DELETE CASCADE,
    UNIQUE (PERMISSION_CODE, PERMISSION_TYPE, PERMISSION_ACTION, TENANT_ID)
);
CREATE INDEX IDX_PERMISSIONS_CODE ON PERMISSIONS(PERMISSION_CODE);
CREATE INDEX IDX_PERMISSIONS_TYPE ON PERMISSIONS(PERMISSION_TYPE);
CREATE INDEX IDX_PERMISSIONS_MENU ON PERMISSIONS(MENU_NO);
CREATE INDEX IDX_PERMISSIONS_TENANT ON PERMISSIONS(TENANT_ID);

-- =====================================================
-- 4. ROLE MANAGEMENT
-- =====================================================

-- Roles table
CREATE TABLE ROLES (
    ROLE_ID VARCHAR(20) NOT NULL,
    ROLE_NAME VARCHAR(100) NOT NULL,
    ROLE_DESCRIPTION VARCHAR(255),
    ROLE_TYPE VARCHAR(80),
    ROLE_SORT_ORDER VARCHAR(10),
    TENANT_ID VARCHAR(20) NOT NULL,
    CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_DATE TIMESTAMP,
    PRIMARY KEY (ROLE_ID),
    FOREIGN KEY (TENANT_ID) REFERENCES TENANTS(TENANT_ID) ON DELETE CASCADE
);
CREATE INDEX IDX_ROLES_TENANT ON ROLES(TENANT_ID);

-- Role-Permission junction table (M:N)
CREATE TABLE ROLE_PERMISSIONS (
    ROLE_PERMISSION_ID BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ROLE_ID VARCHAR(20) NOT NULL,
    PERMISSION_ID BIGINT NOT NULL,
    GRANTED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    GRANTED_BY VARCHAR(20),
    TENANT_ID VARCHAR(20) NOT NULL,
    FOREIGN KEY (ROLE_ID) REFERENCES ROLES(ROLE_ID) ON DELETE CASCADE,
    FOREIGN KEY (PERMISSION_ID) REFERENCES PERMISSIONS(PERMISSION_ID) ON DELETE CASCADE,
    FOREIGN KEY (TENANT_ID) REFERENCES TENANTS(TENANT_ID) ON DELETE CASCADE,
    UNIQUE (ROLE_ID, PERMISSION_ID, TENANT_ID)
);
CREATE INDEX IDX_ROLE_PERMS_ROLE ON ROLE_PERMISSIONS(ROLE_ID);
CREATE INDEX IDX_ROLE_PERMS_PERM ON ROLE_PERMISSIONS(PERMISSION_ID);
CREATE INDEX IDX_ROLE_PERMS_TENANT ON ROLE_PERMISSIONS(TENANT_ID);

-- =====================================================
-- 5. USER MANAGEMENT
-- =====================================================

-- Users table (enhanced with organizational hierarchy)
CREATE TABLE USERS (
    ESNTL_ID VARCHAR(20) NOT NULL PRIMARY KEY,
    USER_ID VARCHAR(20) UNIQUE NOT NULL,
    PASSWORD VARCHAR(255) NOT NULL,
    USER_NAME VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(100),
    PHONE VARCHAR(20),
    GROUP_ID VARCHAR(20),
    BRANCH_ID VARCHAR(20),
    POSITION_ID VARCHAR(20),
    MANAGER_ID VARCHAR(20),
    STATUS_CODE VARCHAR(15),
    TENANT_ID VARCHAR(20) NOT NULL,
    USE_AT CHAR(1) DEFAULT 'Y',
    CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_DATE TIMESTAMP,
    FOREIGN KEY (TENANT_ID) REFERENCES TENANTS(TENANT_ID) ON DELETE CASCADE,
    FOREIGN KEY (GROUP_ID) REFERENCES GROUPS(GROUP_ID),
    FOREIGN KEY (BRANCH_ID) REFERENCES BRANCHES(BRANCH_ID),
    FOREIGN KEY (POSITION_ID) REFERENCES POSITIONS(POSITION_ID),
    FOREIGN KEY (MANAGER_ID) REFERENCES USERS(ESNTL_ID)
);
CREATE INDEX IDX_USERS_TENANT ON USERS(TENANT_ID);
CREATE INDEX IDX_USERS_GROUP ON USERS(GROUP_ID);
CREATE INDEX IDX_USERS_BRANCH ON USERS(BRANCH_ID);
CREATE INDEX IDX_USERS_USER_ID ON USERS(USER_ID);

-- User-Role junction table (M:N - users can have multiple roles)
CREATE TABLE USER_ROLES (
    USER_ROLE_ID BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    USER_ID VARCHAR(20) NOT NULL,
    ROLE_ID VARCHAR(20) NOT NULL,
    ASSIGNED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ASSIGNED_BY VARCHAR(20),
    IS_PRIMARY CHAR(1) DEFAULT 'N',
    TENANT_ID VARCHAR(20) NOT NULL,
    FOREIGN KEY (USER_ID) REFERENCES USERS(ESNTL_ID) ON DELETE CASCADE,
    FOREIGN KEY (ROLE_ID) REFERENCES ROLES(ROLE_ID) ON DELETE CASCADE,
    FOREIGN KEY (TENANT_ID) REFERENCES TENANTS(TENANT_ID) ON DELETE CASCADE,
    UNIQUE (USER_ID, ROLE_ID, TENANT_ID)
);
CREATE INDEX IDX_USER_ROLES_USER ON USER_ROLES(USER_ID);
CREATE INDEX IDX_USER_ROLES_ROLE ON USER_ROLES(ROLE_ID);
CREATE INDEX IDX_USER_ROLES_TENANT ON USER_ROLES(TENANT_ID);

-- Group-Role junction table (roles assigned at group level)
CREATE TABLE GROUP_ROLES (
    GROUP_ROLE_ID BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    GROUP_ID VARCHAR(20) NOT NULL,
    ROLE_ID VARCHAR(20) NOT NULL,
    ASSIGNED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    TENANT_ID VARCHAR(20) NOT NULL,
    FOREIGN KEY (GROUP_ID) REFERENCES GROUPS(GROUP_ID) ON DELETE CASCADE,
    FOREIGN KEY (ROLE_ID) REFERENCES ROLES(ROLE_ID) ON DELETE CASCADE,
    FOREIGN KEY (TENANT_ID) REFERENCES TENANTS(TENANT_ID) ON DELETE CASCADE,
    UNIQUE (GROUP_ID, ROLE_ID, TENANT_ID)
);
CREATE INDEX IDX_GROUP_ROLES_GROUP ON GROUP_ROLES(GROUP_ID);
CREATE INDEX IDX_GROUP_ROLES_ROLE ON GROUP_ROLES(ROLE_ID);
CREATE INDEX IDX_GROUP_ROLES_TENANT ON GROUP_ROLES(TENANT_ID);

-- =====================================================
-- 6. COMMON CODE MANAGEMENT
-- =====================================================

-- Common codes table for system-wide code management
CREATE TABLE COMMON_CODES (
    CODE_ID VARCHAR(6) NOT NULL,
    CLASS_CODE VARCHAR(3),
    CODE_NAME VARCHAR(60),
    CODE_DESCRIPTION VARCHAR(200),
    USE_AT CHAR(1) DEFAULT 'Y',
    TENANT_ID VARCHAR(20),
    CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_DATE TIMESTAMP,
    PRIMARY KEY (CODE_ID)
);
CREATE INDEX IDX_COMMON_CODES_TENANT ON COMMON_CODES(TENANT_ID);
CREATE INDEX IDX_COMMON_CODES_CLASS ON COMMON_CODES(CLASS_CODE);

-- =====================================================
-- 7. FILE MANAGEMENT
-- =====================================================

-- File metadata table
CREATE TABLE FILES (
    ATTACHMENT_FILE_ID VARCHAR(20) NOT NULL,
    CREATED_DATETIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    USE_AT CHAR(1) DEFAULT 'Y',
    TENANT_ID VARCHAR(20),
    PRIMARY KEY (ATTACHMENT_FILE_ID)
);
CREATE INDEX IDX_FILES_TENANT ON FILES(TENANT_ID);

-- File details table
CREATE TABLE FILE_DETAILS (
    DETAIL_ID BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ATTACHMENT_FILE_ID VARCHAR(20),
    FILE_SEQUENCE INT,
    FILE_STORED_PATH VARCHAR(2000),
    STORED_FILE_NAME VARCHAR(255),
    ORIGINAL_FILE_NAME VARCHAR(255),
    FILE_EXTENSION VARCHAR(20),
    FILE_CONTENT TEXT,
    FILE_SIZE BIGINT,
    FOREIGN KEY (ATTACHMENT_FILE_ID) REFERENCES FILES(ATTACHMENT_FILE_ID)
);
CREATE INDEX IDX_FILE_DETAILS_FILE ON FILE_DETAILS(ATTACHMENT_FILE_ID);

-- =====================================================
-- 8. AUDIT & LOGGING
-- =====================================================

-- Permission usage audit log
CREATE TABLE PERMISSION_AUDIT_LOG (
    LOG_ID BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    USER_ID VARCHAR(20) NOT NULL,
    PERMISSION_ID BIGINT NOT NULL,
    ACTION VARCHAR(50),
    RESOURCE_PATH VARCHAR(255),
    ACCESS_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    IP_ADDRESS VARCHAR(45),
    USER_AGENT VARCHAR(255),
    STATUS VARCHAR(20),
    TENANT_ID VARCHAR(20) NOT NULL
);
CREATE INDEX IDX_AUDIT_USER ON PERMISSION_AUDIT_LOG(USER_ID);
CREATE INDEX IDX_AUDIT_TENANT ON PERMISSION_AUDIT_LOG(TENANT_ID);
CREATE INDEX IDX_AUDIT_TIME ON PERMISSION_AUDIT_LOG(ACCESS_TIME);
CREATE INDEX IDX_AUDIT_PERMISSION ON PERMISSION_AUDIT_LOG(PERMISSION_ID);

-- =====================================================
-- END OF SCHEMA INITIALIZATION
-- =====================================================
