-- =====================================================
-- CRM Project - Sales Module Schema Migration
-- Version: V3
-- Description: Creates all tables for Sales Management module
-- Author: CRM Project Team
-- Date: 2026-01-28
-- =====================================================

-- =====================================================
-- 1. CUSTOMER MANAGEMENT
-- =====================================================

-- Customers: Companies or individuals as accounts
CREATE TABLE CUSTOMERS (
    CUSTOMER_ID VARCHAR(20) NOT NULL,
    CUSTOMER_NAME VARCHAR(200) NOT NULL,
    CUSTOMER_CODE VARCHAR(50) NOT NULL,
    CUSTOMER_TYPE VARCHAR(20) DEFAULT 'COMPANY',
    INDUSTRY VARCHAR(50),
    COMPANY_SIZE VARCHAR(20),
    WEBSITE VARCHAR(255),
    PHONE VARCHAR(30),
    EMAIL VARCHAR(100),
    ADDRESS VARCHAR(500),
    ANNUAL_REVENUE DECIMAL(18, 2),
    EMPLOYEE_COUNT INT,
    ASSIGNED_USER_ID VARCHAR(20),
    BRANCH_ID VARCHAR(20),
    TENANT_ID VARCHAR(20) NOT NULL,
    USE_AT CHAR(1) DEFAULT 'Y',
    CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CREATED_BY VARCHAR(20),
    UPDATED_DATE TIMESTAMP,
    UPDATED_BY VARCHAR(20),
    PRIMARY KEY (CUSTOMER_ID),
    FOREIGN KEY (TENANT_ID) REFERENCES TENANTS(TENANT_ID) ON DELETE CASCADE,
    FOREIGN KEY (ASSIGNED_USER_ID) REFERENCES USERS(ESNTL_ID),
    FOREIGN KEY (BRANCH_ID) REFERENCES BRANCHES(BRANCH_ID),
    UNIQUE (CUSTOMER_CODE, TENANT_ID)
);
CREATE INDEX IDX_CUSTOMERS_TENANT ON CUSTOMERS(TENANT_ID);
CREATE INDEX IDX_CUSTOMERS_ASSIGNED ON CUSTOMERS(ASSIGNED_USER_ID);
CREATE INDEX IDX_CUSTOMERS_BRANCH ON CUSTOMERS(BRANCH_ID);
CREATE INDEX IDX_CUSTOMERS_CODE ON CUSTOMERS(CUSTOMER_CODE, TENANT_ID);

-- Contacts: Individual contacts within a customer account
CREATE TABLE CONTACTS (
    CONTACT_ID VARCHAR(20) NOT NULL,
    CUSTOMER_ID VARCHAR(20) NOT NULL,
    CONTACT_NAME VARCHAR(100) NOT NULL,
    CONTACT_TITLE VARCHAR(100),
    DEPARTMENT VARCHAR(100),
    PHONE VARCHAR(30),
    MOBILE VARCHAR(30),
    EMAIL VARCHAR(100),
    IS_PRIMARY CHAR(1) DEFAULT 'N',
    TENANT_ID VARCHAR(20) NOT NULL,
    USE_AT CHAR(1) DEFAULT 'Y',
    CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CREATED_BY VARCHAR(20),
    UPDATED_DATE TIMESTAMP,
    PRIMARY KEY (CONTACT_ID),
    FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMERS(CUSTOMER_ID) ON DELETE CASCADE,
    FOREIGN KEY (TENANT_ID) REFERENCES TENANTS(TENANT_ID) ON DELETE CASCADE
);
CREATE INDEX IDX_CONTACTS_TENANT ON CONTACTS(TENANT_ID);
CREATE INDEX IDX_CONTACTS_CUSTOMER ON CONTACTS(CUSTOMER_ID);

-- =====================================================
-- 2. LEAD MANAGEMENT
-- =====================================================

-- Leads: Potential customers before conversion
CREATE TABLE LEADS (
    LEAD_ID VARCHAR(20) NOT NULL,
    LEAD_NAME VARCHAR(200) NOT NULL,
    COMPANY_NAME VARCHAR(200),
    CONTACT_NAME VARCHAR(100),
    EMAIL VARCHAR(100),
    PHONE VARCHAR(30),
    LEAD_SOURCE VARCHAR(50),
    LEAD_STATUS VARCHAR(20) DEFAULT 'NEW',
    LEAD_SCORE INT DEFAULT 0,
    INDUSTRY VARCHAR(50),
    ESTIMATED_REVENUE DECIMAL(18, 2),
    DESCRIPTION TEXT,
    ASSIGNED_USER_ID VARCHAR(20),
    CONVERTED_CUSTOMER_ID VARCHAR(20),
    CONVERTED_DATE TIMESTAMP,
    TENANT_ID VARCHAR(20) NOT NULL,
    USE_AT CHAR(1) DEFAULT 'Y',
    CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CREATED_BY VARCHAR(20),
    UPDATED_DATE TIMESTAMP,
    PRIMARY KEY (LEAD_ID),
    FOREIGN KEY (TENANT_ID) REFERENCES TENANTS(TENANT_ID) ON DELETE CASCADE,
    FOREIGN KEY (ASSIGNED_USER_ID) REFERENCES USERS(ESNTL_ID),
    FOREIGN KEY (CONVERTED_CUSTOMER_ID) REFERENCES CUSTOMERS(CUSTOMER_ID)
);
CREATE INDEX IDX_LEADS_TENANT ON LEADS(TENANT_ID);
CREATE INDEX IDX_LEADS_STATUS ON LEADS(LEAD_STATUS, TENANT_ID);
CREATE INDEX IDX_LEADS_ASSIGNED ON LEADS(ASSIGNED_USER_ID);

-- =====================================================
-- 3. PRODUCT CATALOG
-- =====================================================

-- Products: Products and services offered
CREATE TABLE PRODUCTS (
    PRODUCT_ID VARCHAR(20) NOT NULL,
    PRODUCT_CODE VARCHAR(50) NOT NULL,
    PRODUCT_NAME VARCHAR(200) NOT NULL,
    PRODUCT_CATEGORY VARCHAR(50),
    PRODUCT_TYPE VARCHAR(20) DEFAULT 'PRODUCT',
    DESCRIPTION TEXT,
    UNIT_PRICE DECIMAL(18, 2) NOT NULL,
    COST_PRICE DECIMAL(18, 2),
    CURRENCY VARCHAR(3) DEFAULT 'KRW',
    TAX_RATE DECIMAL(5, 2) DEFAULT 10.00,
    STOCK_QUANTITY INT DEFAULT 0,
    IS_ACTIVE CHAR(1) DEFAULT 'Y',
    TENANT_ID VARCHAR(20) NOT NULL,
    USE_AT CHAR(1) DEFAULT 'Y',
    CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CREATED_BY VARCHAR(20),
    UPDATED_DATE TIMESTAMP,
    PRIMARY KEY (PRODUCT_ID),
    FOREIGN KEY (TENANT_ID) REFERENCES TENANTS(TENANT_ID) ON DELETE CASCADE,
    UNIQUE (PRODUCT_CODE, TENANT_ID)
);
CREATE INDEX IDX_PRODUCTS_TENANT ON PRODUCTS(TENANT_ID);
CREATE INDEX IDX_PRODUCTS_CODE ON PRODUCTS(PRODUCT_CODE, TENANT_ID);
CREATE INDEX IDX_PRODUCTS_CATEGORY ON PRODUCTS(PRODUCT_CATEGORY, TENANT_ID);

-- =====================================================
-- 4. SALES PIPELINE
-- =====================================================

-- Pipeline Stages: Customizable sales pipeline stages per tenant
CREATE TABLE PIPELINE_STAGES (
    STAGE_ID VARCHAR(20) NOT NULL,
    STAGE_NAME VARCHAR(100) NOT NULL,
    STAGE_CODE VARCHAR(50) NOT NULL,
    STAGE_ORDER INT DEFAULT 0,
    PROBABILITY INT DEFAULT 0,
    STAGE_COLOR VARCHAR(7),
    IS_WON CHAR(1) DEFAULT 'N',
    IS_LOST CHAR(1) DEFAULT 'N',
    TENANT_ID VARCHAR(20) NOT NULL,
    USE_AT CHAR(1) DEFAULT 'Y',
    CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_DATE TIMESTAMP,
    PRIMARY KEY (STAGE_ID),
    FOREIGN KEY (TENANT_ID) REFERENCES TENANTS(TENANT_ID) ON DELETE CASCADE,
    UNIQUE (STAGE_CODE, TENANT_ID)
);
CREATE INDEX IDX_PIPELINE_STAGES_TENANT ON PIPELINE_STAGES(TENANT_ID);
CREATE INDEX IDX_PIPELINE_STAGES_ORDER ON PIPELINE_STAGES(STAGE_ORDER, TENANT_ID);

-- =====================================================
-- 5. OPPORTUNITY MANAGEMENT
-- =====================================================

-- Opportunities: Sales deals and potential revenue
CREATE TABLE OPPORTUNITIES (
    OPPORTUNITY_ID VARCHAR(20) NOT NULL,
    OPPORTUNITY_NAME VARCHAR(200) NOT NULL,
    CUSTOMER_ID VARCHAR(20) NOT NULL,
    CONTACT_ID VARCHAR(20),
    STAGE_ID VARCHAR(20) NOT NULL,
    AMOUNT DECIMAL(18, 2),
    PROBABILITY INT DEFAULT 0,
    EXPECTED_CLOSE_DATE DATE,
    ACTUAL_CLOSE_DATE DATE,
    LEAD_SOURCE VARCHAR(50),
    DESCRIPTION TEXT,
    NEXT_STEP VARCHAR(500),
    COMPETITOR_INFO TEXT,
    ASSIGNED_USER_ID VARCHAR(20),
    BRANCH_ID VARCHAR(20),
    WON_REASON VARCHAR(500),
    LOST_REASON VARCHAR(500),
    TENANT_ID VARCHAR(20) NOT NULL,
    USE_AT CHAR(1) DEFAULT 'Y',
    CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CREATED_BY VARCHAR(20),
    UPDATED_DATE TIMESTAMP,
    UPDATED_BY VARCHAR(20),
    PRIMARY KEY (OPPORTUNITY_ID),
    FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMERS(CUSTOMER_ID),
    FOREIGN KEY (CONTACT_ID) REFERENCES CONTACTS(CONTACT_ID),
    FOREIGN KEY (STAGE_ID) REFERENCES PIPELINE_STAGES(STAGE_ID),
    FOREIGN KEY (ASSIGNED_USER_ID) REFERENCES USERS(ESNTL_ID),
    FOREIGN KEY (BRANCH_ID) REFERENCES BRANCHES(BRANCH_ID),
    FOREIGN KEY (TENANT_ID) REFERENCES TENANTS(TENANT_ID) ON DELETE CASCADE
);
CREATE INDEX IDX_OPPORTUNITIES_TENANT ON OPPORTUNITIES(TENANT_ID);
CREATE INDEX IDX_OPPORTUNITIES_CUSTOMER ON OPPORTUNITIES(CUSTOMER_ID);
CREATE INDEX IDX_OPPORTUNITIES_STAGE ON OPPORTUNITIES(STAGE_ID);
CREATE INDEX IDX_OPPORTUNITIES_CLOSE_DATE ON OPPORTUNITIES(EXPECTED_CLOSE_DATE, TENANT_ID);
CREATE INDEX IDX_OPPORTUNITIES_ASSIGNED ON OPPORTUNITIES(ASSIGNED_USER_ID);

-- Opportunity Products: Products linked to opportunities
CREATE TABLE OPPORTUNITY_PRODUCTS (
    OPP_PRODUCT_ID BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    OPPORTUNITY_ID VARCHAR(20) NOT NULL,
    PRODUCT_ID VARCHAR(20) NOT NULL,
    QUANTITY INT DEFAULT 1,
    UNIT_PRICE DECIMAL(18, 2) NOT NULL,
    DISCOUNT_RATE DECIMAL(5, 2) DEFAULT 0,
    DISCOUNT_AMOUNT DECIMAL(18, 2) DEFAULT 0,
    TOTAL_AMOUNT DECIMAL(18, 2) NOT NULL,
    TENANT_ID VARCHAR(20) NOT NULL,
    CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_DATE TIMESTAMP,
    FOREIGN KEY (OPPORTUNITY_ID) REFERENCES OPPORTUNITIES(OPPORTUNITY_ID) ON DELETE CASCADE,
    FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCTS(PRODUCT_ID),
    FOREIGN KEY (TENANT_ID) REFERENCES TENANTS(TENANT_ID) ON DELETE CASCADE
);
CREATE INDEX IDX_OPP_PRODUCTS_TENANT ON OPPORTUNITY_PRODUCTS(TENANT_ID);
CREATE INDEX IDX_OPP_PRODUCTS_OPP ON OPPORTUNITY_PRODUCTS(OPPORTUNITY_ID);

-- =====================================================
-- 6. QUOTE MANAGEMENT
-- =====================================================

-- Quotes: Formal price proposals to customers
CREATE TABLE QUOTES (
    QUOTE_ID VARCHAR(20) NOT NULL,
    QUOTE_NUMBER VARCHAR(50) NOT NULL,
    OPPORTUNITY_ID VARCHAR(20),
    CUSTOMER_ID VARCHAR(20) NOT NULL,
    CONTACT_ID VARCHAR(20),
    QUOTE_STATUS VARCHAR(20) DEFAULT 'DRAFT',
    QUOTE_DATE DATE NOT NULL,
    VALID_UNTIL DATE,
    SUBTOTAL DECIMAL(18, 2) DEFAULT 0,
    DISCOUNT_AMOUNT DECIMAL(18, 2) DEFAULT 0,
    TAX_AMOUNT DECIMAL(18, 2) DEFAULT 0,
    TOTAL_AMOUNT DECIMAL(18, 2) DEFAULT 0,
    CURRENCY VARCHAR(3) DEFAULT 'KRW',
    PAYMENT_TERMS VARCHAR(200),
    DELIVERY_TERMS VARCHAR(200),
    NOTES TEXT,
    ASSIGNED_USER_ID VARCHAR(20),
    TENANT_ID VARCHAR(20) NOT NULL,
    USE_AT CHAR(1) DEFAULT 'Y',
    CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CREATED_BY VARCHAR(20),
    UPDATED_DATE TIMESTAMP,
    PRIMARY KEY (QUOTE_ID),
    FOREIGN KEY (OPPORTUNITY_ID) REFERENCES OPPORTUNITIES(OPPORTUNITY_ID),
    FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMERS(CUSTOMER_ID),
    FOREIGN KEY (CONTACT_ID) REFERENCES CONTACTS(CONTACT_ID),
    FOREIGN KEY (ASSIGNED_USER_ID) REFERENCES USERS(ESNTL_ID),
    FOREIGN KEY (TENANT_ID) REFERENCES TENANTS(TENANT_ID) ON DELETE CASCADE,
    UNIQUE (QUOTE_NUMBER, TENANT_ID)
);
CREATE INDEX IDX_QUOTES_TENANT ON QUOTES(TENANT_ID);
CREATE INDEX IDX_QUOTES_CUSTOMER ON QUOTES(CUSTOMER_ID);
CREATE INDEX IDX_QUOTES_OPPORTUNITY ON QUOTES(OPPORTUNITY_ID);
CREATE INDEX IDX_QUOTES_STATUS ON QUOTES(QUOTE_STATUS, TENANT_ID);

-- Quote Items: Individual line items in quotes
CREATE TABLE QUOTE_ITEMS (
    QUOTE_ITEM_ID BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    QUOTE_ID VARCHAR(20) NOT NULL,
    PRODUCT_ID VARCHAR(20) NOT NULL,
    ITEM_ORDER INT DEFAULT 0,
    QUANTITY INT DEFAULT 1,
    UNIT_PRICE DECIMAL(18, 2) NOT NULL,
    DISCOUNT_RATE DECIMAL(5, 2) DEFAULT 0,
    DISCOUNT_AMOUNT DECIMAL(18, 2) DEFAULT 0,
    TAX_RATE DECIMAL(5, 2) DEFAULT 10.00,
    TAX_AMOUNT DECIMAL(18, 2) DEFAULT 0,
    TOTAL_AMOUNT DECIMAL(18, 2) NOT NULL,
    DESCRIPTION VARCHAR(500),
    TENANT_ID VARCHAR(20) NOT NULL,
    CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_DATE TIMESTAMP,
    FOREIGN KEY (QUOTE_ID) REFERENCES QUOTES(QUOTE_ID) ON DELETE CASCADE,
    FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCTS(PRODUCT_ID),
    FOREIGN KEY (TENANT_ID) REFERENCES TENANTS(TENANT_ID) ON DELETE CASCADE
);
CREATE INDEX IDX_QUOTE_ITEMS_TENANT ON QUOTE_ITEMS(TENANT_ID);
CREATE INDEX IDX_QUOTE_ITEMS_QUOTE ON QUOTE_ITEMS(QUOTE_ID);

-- =====================================================
-- 7. ACTIVITY TRACKING
-- =====================================================

-- Activities: Tasks, calls, meetings, notes
CREATE TABLE ACTIVITIES (
    ACTIVITY_ID VARCHAR(20) NOT NULL,
    ACTIVITY_TYPE VARCHAR(20) NOT NULL,
    ACTIVITY_SUBJECT VARCHAR(200) NOT NULL,
    ACTIVITY_DESCRIPTION TEXT,
    ACTIVITY_STATUS VARCHAR(20) DEFAULT 'PLANNED',
    ACTIVITY_DATE TIMESTAMP,
    DUE_DATE TIMESTAMP,
    COMPLETED_DATE TIMESTAMP,
    DURATION_MINUTES INT,
    PRIORITY VARCHAR(10) DEFAULT 'NORMAL',
    RELATED_TYPE VARCHAR(20),
    RELATED_ID VARCHAR(20),
    ASSIGNED_USER_ID VARCHAR(20),
    TENANT_ID VARCHAR(20) NOT NULL,
    USE_AT CHAR(1) DEFAULT 'Y',
    CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CREATED_BY VARCHAR(20),
    UPDATED_DATE TIMESTAMP,
    PRIMARY KEY (ACTIVITY_ID),
    FOREIGN KEY (ASSIGNED_USER_ID) REFERENCES USERS(ESNTL_ID),
    FOREIGN KEY (TENANT_ID) REFERENCES TENANTS(TENANT_ID) ON DELETE CASCADE
);
CREATE INDEX IDX_ACTIVITIES_TENANT ON ACTIVITIES(TENANT_ID);
CREATE INDEX IDX_ACTIVITIES_RELATED ON ACTIVITIES(RELATED_TYPE, RELATED_ID, TENANT_ID);
CREATE INDEX IDX_ACTIVITIES_ASSIGNED ON ACTIVITIES(ASSIGNED_USER_ID, ACTIVITY_STATUS);
CREATE INDEX IDX_ACTIVITIES_DUE ON ACTIVITIES(DUE_DATE, TENANT_ID);

-- =====================================================
-- 8. SALES TARGETS
-- =====================================================

-- Sales Targets: Revenue and deal goals
CREATE TABLE SALES_TARGETS (
    TARGET_ID VARCHAR(20) NOT NULL,
    TARGET_YEAR INT NOT NULL,
    TARGET_MONTH INT,
    TARGET_AMOUNT DECIMAL(18, 2) NOT NULL,
    ACHIEVED_AMOUNT DECIMAL(18, 2) DEFAULT 0,
    TARGET_TYPE VARCHAR(20) DEFAULT 'REVENUE',
    USER_ID VARCHAR(20),
    BRANCH_ID VARCHAR(20),
    TENANT_ID VARCHAR(20) NOT NULL,
    CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_DATE TIMESTAMP,
    PRIMARY KEY (TARGET_ID),
    FOREIGN KEY (USER_ID) REFERENCES USERS(ESNTL_ID),
    FOREIGN KEY (BRANCH_ID) REFERENCES BRANCHES(BRANCH_ID),
    FOREIGN KEY (TENANT_ID) REFERENCES TENANTS(TENANT_ID) ON DELETE CASCADE,
    UNIQUE (TARGET_YEAR, TARGET_MONTH, TARGET_TYPE, USER_ID, BRANCH_ID, TENANT_ID)
);
CREATE INDEX IDX_SALES_TARGETS_TENANT ON SALES_TARGETS(TENANT_ID);
CREATE INDEX IDX_SALES_TARGETS_YEAR ON SALES_TARGETS(TARGET_YEAR, TARGET_MONTH, TENANT_ID);
CREATE INDEX IDX_SALES_TARGETS_USER ON SALES_TARGETS(USER_ID);

-- =====================================================
-- END OF SALES MODULE SCHEMA
-- =====================================================
